### Fetch all persons
GET http://localhost:3001/api/persons

### Fetch single person
GET http://localhost:3001/api/persons/1

### Delete person
DELETE http://localhost:3001/api/persons/64bac09ce9bfc0a5f94c7fc8

### Fetch all persons after deletion
GET http://localhost:3001/api/persons

### Add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "New Person",
    "number": "12-34-567890"
}

### Add new person without number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Missing Number"
}

###

### Add new person without name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "12-34-567890"
}

###

### Add new person with duplicate name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "99-99-999999"
}

###

### Add new person with duplicate number
PUT http://localhost:3001/api/persons/64bac06a950811db2a81e37b HTTP/1.1
content-type: application/json

{
    "name": "Updated Name",
    "number": "Updated Number"
}
